// Shared enums. Kept in one place so models, guards and the frontend all agree
// on the exact strings.

const ROLES = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  ORG_MEMBER: 'ORG_MEMBER',
};

const ORG_STATUS = {
  PENDING: 'PENDING',
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  CANCELLED: 'CANCELLED',
};

const USER_STATUS = {
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
};

const SUBSCRIPTION_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  ROLLED_BACK: 'ROLLED_BACK',
};

const TRANSACTION_TYPE = {
  SUBSCRIPTION_CREATE: 'SUBSCRIPTION_CREATE',
  RENEWAL: 'RENEWAL',
  UPGRADE: 'UPGRADE',
  DOWNGRADE: 'DOWNGRADE',
  CANCELLATION: 'CANCELLATION',
  REFUND: 'REFUND',
};

const BILLING_INTERVAL = {
  MONTH: 'month',
  YEAR: 'year',
};

module.exports = {
  ROLES,
  ORG_STATUS,
  USER_STATUS,
  SUBSCRIPTION_STATUS,
  PAYMENT_STATUS,
  TRANSACTION_STATUS,
  TRANSACTION_TYPE,
  BILLING_INTERVAL,
};
